// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhCNhv_lOmVlCEVOx5eIf1nPlQq6UuxMk',
    appId: '1:207966505420:web:7467fb538100303c9f7569',
    messagingSenderId: '207966505420',
    projectId: 'campustrade-b8b0b',
    authDomain: 'campustrade-b8b0b.firebaseapp.com',
    storageBucket: 'campustrade-b8b0b.firebasestorage.app',
    measurementId: 'G-9XKZG0W8SK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3_h-dE2ymE2_FZmMY3lHOKUht3joyUOI',
    appId: '1:207966505420:android:cd31d3030c20e7d79f7569',
    messagingSenderId: '207966505420',
    projectId: 'campustrade-b8b0b',
    storageBucket: 'campustrade-b8b0b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArB9CNBvVgBwYgt9HYKEV4BkXbsnk2_DY',
    appId: '1:207966505420:ios:10eb2af5a42074a39f7569',
    messagingSenderId: '207966505420',
    projectId: 'campustrade-b8b0b',
    storageBucket: 'campustrade-b8b0b.firebasestorage.app',
    iosBundleId: 'com.example.campustrade',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArB9CNBvVgBwYgt9HYKEV4BkXbsnk2_DY',
    appId: '1:207966505420:ios:10eb2af5a42074a39f7569',
    messagingSenderId: '207966505420',
    projectId: 'campustrade-b8b0b',
    storageBucket: 'campustrade-b8b0b.firebasestorage.app',
    iosBundleId: 'com.example.campustrade',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhCNhv_lOmVlCEVOx5eIf1nPlQq6UuxMk',
    appId: '1:207966505420:web:e2a786381a3c46a19f7569',
    messagingSenderId: '207966505420',
    projectId: 'campustrade-b8b0b',
    authDomain: 'campustrade-b8b0b.firebaseapp.com',
    storageBucket: 'campustrade-b8b0b.firebasestorage.app',
    measurementId: 'G-7K95KVL7VW',
  );
}
